const result=document.getElementById('result'),q=document.getElementById('q'),portrait=document.getElementById('portrait');let data,index=0;
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>s.slice(3,8);
function active(mode){document.getElementById('pearl').classList.toggle('active',mode==='pearl');document.getElementById('question').classList.toggle('active',mode==='question')}
function pearl(){if(!data)return;active('pearl');const p=data.quotes[index++%data.quotes.length];result.innerHTML=`<div class="label">${escape(p.title)}</div><blockquote class="quote">“${escape(p.text)}”</blockquote><div class="source">John Scalzo · Interview ${time(p.time)}</div>`;portrait.classList.remove('bump');void portrait.offsetWidth;portrait.classList.add('bump')}
const stop=new Set('how should i the a an is are do does can what my me of to about in on and why it for with would tell be you we this that much'.split(' '));
function words(s){return s.toLowerCase().replace(/labour/g,'labor').replace(/pricing|priced/g,'price').replace(/staffing/g,'staff').match(/[a-z0-9]+/g)?.filter(x=>!stop.has(x))||[]}
function ask(){if(!data)return;active('question');const question=q.value.trim();if(!question)return;if(/^(give|tell|provide|show).*(quote|pearl)|^quote$/i.test(question)){pearl();return}const terms=words(question);const ranked=data.sections.map(s=>{const ks=words(s.keywords+' '+s.title);return {s,score:terms.reduce((v,t)=>v+(ks.includes(t)?4:0)+(words(s.title).includes(t)?2:0),0)}}).sort((a,b)=>b.score-a.score);if(!terms.length||!ranked[0].score){result.innerHTML='<div class="label">Outside the interview</div><p class="quote">I couldn’t find a clear match in this interview.</p><p class="source">Try asking about cash flow, staff, menu costing, waste, or running a cafe. Lesson text hasn’t been added to this prototype yet.</p>';return}const s=ranked[0].s;const cues=s.text.split(/(?<=[.!?])\s+/);const scored=cues.map((text,i)=>({text,i,score:words(text).filter(t=>terms.includes(t)).length})).sort((a,b)=>b.score-a.score);let excerpt=cues.slice(Math.max(0,scored[0].i-1),scored[0].i+3).join(' ');result.innerHTML=`<div class="label">Relevant interview passage · ${escape(s.title)}</div><p style="font:21px/1.5 Georgia,serif;margin:18px 0">${escape(excerpt)}</p><div class="source">Matt Perger & John Scalzo · From ${time(s.time)}</div><details><summary>Read the full passage</summary><p>${escape(s.text)}</p></details>`}
document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();ask()});portrait.addEventListener('click',pearl);document.getElementById('pearl').addEventListener('click',pearl);document.getElementById('question').addEventListener('click',()=>{active('question');q.focus()});document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{q.value=b.dataset.q;ask()}));data=window.SCALZO_DATA;pearl();
